name: jhgjhg
favicon: null
layout_spectrum: 0.717335098888725
typography_spectrum: 0.06421115924604237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4907902895938605
  lightness: 0.10829424858093262
  saturation: 0.9497267273254693
  rhythmicContrast: 0.3055993067100644
purpose: []
